### ISSUE TITLE
[Feature request] Ability to hide boot entries

### ISSUE THREAD

**Issue by zjeffer** [kgoettler/ursamajor-rEFInd#4]
In the default rEFInd theme, you can press delete to hide an entry from the list. A confirmation window will pop up, asking if the user truly wants to hide the boot entry, with 'yes' or 'no'.

With this theme, pressing delete flickers the screen, but doesn't do anything else, as if the confirmation window immediately picks 'no'. 

It would be nice if we could hide boot entries with this theme as well.

**Comment by LeonRein** [comment]
You can only hide menu entries, if the "hidden_tags" tool is enabled. This enables the menu icon in the bottom row, where all hidden entries are managed. To enable it, you can change the respective line in theme.conf to `showtools shutdown,hidden_tags`. But it looks a bit like crap since the logo is not themed.

**Comment by zjeffer** [comment]
@LeonRein I see. Is it possible to bind a shortcut to open the hidden tags menu, instead of having a button added?

**Comment by zjeffer** [comment]
I added `func_hidden.png` from [this repository](https://github.com/lukechilds/refind-ambience/blob/master/icons/func_hidden.png) to my icons folder, which blends into this theme quite well.
